### ISSUE TITLE
User can search for meals based on category or type of dish

### ISSUE THREAD

**Issue by Mohamed-Elmessiry** [Mohamed-Elmessiry/ajax-project#1]
## ⚙️ Feature

User can search for meals based on category or type of dish.

## 📐 Functionality

User will have the ability to type food preferences, selecting by category (meat, chicken, fish) or by cuisine (Main course, dessert)

## 🖼️ Wireframes

<img width="1440" alt="Screen Shot 2021-04-14 at 10 54 25 AM" src="https://user-images.githubusercontent.com/69738204/114731788-0393fd80-9d10-11eb-8677-f9f23a794433.png">

## ✅ Task List

- [x]  Create a header containing links to main page and favorites
- [x] Create the body with an H2 element
- [x] Create an input section underneath the H2 element
- [x] Create a select search type dropdown  selector
- [x] Create a search button
- [x] Make sure it looks good on mobile and desktop
- [x] Add event listener for search button
- [x] Create a function to request data from the API using the search term provided by the user
- [x] Make correct type of request based on type of search from user (category or cuisine)
