### ISSUE TITLE
User can view list of results

### ISSUE THREAD

**Issue by Mohamed-Elmessiry** [Mohamed-Elmessiry/ajax-project#2]
## ⚙️ Feature

User can view list of results

## 📐 Functionality

Based on the previous step of typing preferences. The user will have the ability to see images and dish titles resulting from their search

## 🖼️ Wireframes

<img width="1440" alt="Screen Shot 2021-04-14 at 10 54 33 AM" src="https://user-images.githubusercontent.com/69738204/114735422-24aa1d80-9d13-11eb-817e-69feea2bba1d.png">

## ✅ Task List

- [x] Create a div to hold results (class results)
- [x] Create a function to create a DOM tree holding results
- [x] loop over search results and append the image element and the name of the main dish
- [x] append all elements created in the div in the first step
- [x] Style the created elements in the Dom tree according to the wire frames
- [x] Create a class for the header adjusting color, upon displaying results
- [x] listen to the main page button allowing users to head back to the homepage
