### ISSUE TITLE
User can view detail for a single recipe

### ISSUE THREAD

**Issue by Mohamed-Elmessiry** [Mohamed-Elmessiry/ajax-project#3]
## ⚙️ Feature

User can view detail view for a single recipe

## 📐 Functionality

After screening initial search results, user will have the ability to select a dish, which would give an entire view of the page containing an image of the dish, the name , ingredients ,also a link to the full recipe and a button to save as favorites

## 🖼️ Wireframes

<img width="1440" alt="Screen Shot 2021-04-14 at 10 54 30 AM" src="https://user-images.githubusercontent.com/69738204/114737766-5623e880-9d15-11eb-8f7a-501d4baa1fdb.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a string Ingredients to dom tree result holder and set it to a class of hidden
- [x] Add a the ingredients from the api and set it to a class of of hidden
- [x] Add a button for view full recipe
- [x] Add a button for save to favorites
- [x] query the dom for a node list of all elements with a class of 'result holder'
- [x] add a click event listener to class of results (the parent element) to check if event.target 
matches result holder
- [x] loop through all the node list result holder and compare each of them to event.target
- [x] if the element does not match event.target, then it should have a class of hidden
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
