### ISSUE TITLE
User can save recipe to favorites

### ISSUE THREAD

**Issue by Mohamed-Elmessiry** [Mohamed-Elmessiry/ajax-project#4]
## ⚙️ Feature

User can save recipe to favorites

## 📐 Functionality

After having the opportunity to look at a single dish, the user will have the ability to select this dish as favorite item

## 🖼️ Wireframes

<img width="1440" alt="Screen Shot 2021-04-14 at 10 54 52 AM" src="https://user-images.githubusercontent.com/69738204/114739422-dac33680-9d16-11eb-8061-6dbe22234b06.png">

## ✅ Task List

- [x] Add an event listener to save button 
- [x] Add an object to the function in the event listener, allowing it to capture data inserting it to the object
- [x] Add a data variable in data.js to save the favorites
- [x] unshift entries from the object to the data model
- [x] Add local storage to save favorites
- [x] Add a div in html to display favorites
- [x] Add event listener for favorites button allowing it to loop over saved data
- **Clean Up**
  - 
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
