### ISSUE TITLE
User can add note to favorited recipe

### ISSUE THREAD

**Issue by Mohamed-Elmessiry** [Mohamed-Elmessiry/ajax-project#5]
## ⚙️ Feature

User can add note to favorited recipe

## 📐 Functionality

After selecting the dish as a favorite in the previous feature, user will have the ability to a note through a modal pop up

## 🖼️ Wireframes

<img width="1440" alt="Screen Shot 2021-04-14 at 10 54 54 AM" src="https://user-images.githubusercontent.com/69738204/114740353-c5024100-9d17-11eb-8a6e-d33e5571e76d.png">

## ✅ Task List

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
